export interface ShowcasePhoto {
  id: string
  src: string
  alt: string
}

// Real event photos from the Envision program.
export const SHOWCASE_PHOTOS: ShowcasePhoto[] = [
  { id: 'day2-01', src: '/showcase/day2-01.jpg', alt: 'Envision — day2 01' },
  { id: 'day2-02', src: '/showcase/day2-02.jpg', alt: 'Envision — day2 02' },
  { id: 'day2-03', src: '/showcase/day2-03.jpg', alt: 'Envision — day2 03' },
  { id: 'day2-04', src: '/showcase/day2-04.jpg', alt: 'Envision — day2 04' },
  { id: 'day2-05', src: '/showcase/day2-05.jpg', alt: 'Envision — day2 05' },
  { id: 'day2-06', src: '/showcase/day2-06.jpg', alt: 'Envision — day2 06' },
  { id: 'day2-07', src: '/showcase/day2-07.jpg', alt: 'Envision — day2 07' },
  { id: 'day2-08', src: '/showcase/day2-08.jpg', alt: 'Envision — day2 08' },
  { id: 'day2-09', src: '/showcase/day2-09.jpg', alt: 'Envision — day2 09' },
  { id: 'day2-10', src: '/showcase/day2-10.jpeg', alt: 'Envision — day2 10' },
  { id: 'day2-11', src: '/showcase/day2-11.jpeg', alt: 'Envision — day2 11' },
  { id: 'day2-12', src: '/showcase/day2-12.jpeg', alt: 'Envision — day2 12' },
  { id: 'day2-13', src: '/showcase/day2-13.jpeg', alt: 'Envision — day2 13' },
  { id: 'day2-14', src: '/showcase/day2-14.jpeg', alt: 'Envision — day2 14' },
  { id: 'idea-presentation-01', src: '/showcase/idea-presentation-01.jpg', alt: 'Envision — idea presentation 01' },
  { id: 'idea-presentation-02', src: '/showcase/idea-presentation-02.jpg', alt: 'Envision — idea presentation 02' },
  { id: 'idea-presentation-03', src: '/showcase/idea-presentation-03.jpg', alt: 'Envision — idea presentation 03' },
  { id: 'idea-presentation-04', src: '/showcase/idea-presentation-04.jpg', alt: 'Envision — idea presentation 04' },
  { id: 'idea-presentation-05', src: '/showcase/idea-presentation-05.jpg', alt: 'Envision — idea presentation 05' },
  { id: 'idea-presentation-06', src: '/showcase/idea-presentation-06.jpg', alt: 'Envision — idea presentation 06' },
  { id: 'idea-presentation-07', src: '/showcase/idea-presentation-07.jpg', alt: 'Envision — idea presentation 07' },
  { id: 'idea-presentation-08', src: '/showcase/idea-presentation-08.jpeg', alt: 'Envision — idea presentation 08' },
  { id: 'idea-presentation-09', src: '/showcase/idea-presentation-09.jpeg', alt: 'Envision — idea presentation 09' },
  { id: 'idea-presentation-10', src: '/showcase/idea-presentation-10.jpeg', alt: 'Envision — idea presentation 10' },
  { id: 'idea-presentation-11', src: '/showcase/idea-presentation-11.jpeg', alt: 'Envision — idea presentation 11' },
  { id: 'idea-presentation-12', src: '/showcase/idea-presentation-12.jpeg', alt: 'Envision — idea presentation 12' },
  { id: 'workshop-day1-01', src: '/showcase/workshop-day1-01.jpg', alt: 'Envision — workshop day1 01' },
  { id: 'workshop-day1-02', src: '/showcase/workshop-day1-02.jpg', alt: 'Envision — workshop day1 02' },
  { id: 'workshop-day1-03', src: '/showcase/workshop-day1-03.jpg', alt: 'Envision — workshop day1 03' },
  { id: 'workshop-day1-04', src: '/showcase/workshop-day1-04.jpg', alt: 'Envision — workshop day1 04' },
  { id: 'workshop-day1-05', src: '/showcase/workshop-day1-05.jpg', alt: 'Envision — workshop day1 05' },
  { id: 'workshop-day1-06', src: '/showcase/workshop-day1-06.jpg', alt: 'Envision — workshop day1 06' },
  { id: 'workshop-day1-07', src: '/showcase/workshop-day1-07.jpg', alt: 'Envision — workshop day1 07' },
  { id: 'workshop-day1-08', src: '/showcase/workshop-day1-08.jpg', alt: 'Envision — workshop day1 08' },
  { id: 'workshop-day1-09', src: '/showcase/workshop-day1-09.jpg', alt: 'Envision — workshop day1 09' },
  { id: 'workshop-day1-10', src: '/showcase/workshop-day1-10.jpg', alt: 'Envision — workshop day1 10' },
  { id: 'workshop-day1-11', src: '/showcase/workshop-day1-11.jpg', alt: 'Envision — workshop day1 11' },
  { id: 'workshop-day1-12', src: '/showcase/workshop-day1-12.jpg', alt: 'Envision — workshop day1 12' },
  { id: 'workshop-day1-13', src: '/showcase/workshop-day1-13.jpg', alt: 'Envision — workshop day1 13' },
  { id: 'workshop-day1-14', src: '/showcase/workshop-day1-14.jpg', alt: 'Envision — workshop day1 14' },
  { id: 'workshop-day1-15', src: '/showcase/workshop-day1-15.jpg', alt: 'Envision — workshop day1 15' },
  { id: 'workshop-day1-16', src: '/showcase/workshop-day1-16.jpg', alt: 'Envision — workshop day1 16' },
  { id: 'workshop-day1-17', src: '/showcase/workshop-day1-17.jpg', alt: 'Envision — workshop day1 17' },
  { id: 'workshop-day1-18', src: '/showcase/workshop-day1-18.jpg', alt: 'Envision — workshop day1 18' },
  { id: 'workshop-day1-19', src: '/showcase/workshop-day1-19.jpg', alt: 'Envision — workshop day1 19' },
  { id: 'workshop-day1-20', src: '/showcase/workshop-day1-20.jpg', alt: 'Envision — workshop day1 20' },
  { id: 'workshop-day1-21', src: '/showcase/workshop-day1-21.jpg', alt: 'Envision — workshop day1 21' },
  { id: 'workshop-day1-22', src: '/showcase/workshop-day1-22.jpg', alt: 'Envision — workshop day1 22' },
  { id: 'workshop-day1-23', src: '/showcase/workshop-day1-23.jpg', alt: 'Envision — workshop day1 23' },
  { id: 'workshop-day1-24', src: '/showcase/workshop-day1-24.jpg', alt: 'Envision — workshop day1 24' },
  { id: 'workshop-day1-25', src: '/showcase/workshop-day1-25.jpg', alt: 'Envision — workshop day1 25' },
  { id: 'workshop-day1-26', src: '/showcase/workshop-day1-26.jpg', alt: 'Envision — workshop day1 26' },
  { id: 'workshop-day1-27', src: '/showcase/workshop-day1-27.jpg', alt: 'Envision — workshop day1 27' },
  { id: 'workshop-day1-28', src: '/showcase/workshop-day1-28.jpg', alt: 'Envision — workshop day1 28' },
  { id: 'workshop-day2-01', src: '/showcase/workshop-day2-01.jpg', alt: 'Envision — workshop day2 01' },
  { id: 'workshop-day2-02', src: '/showcase/workshop-day2-02.jpg', alt: 'Envision — workshop day2 02' },
  { id: 'workshop-day2-03', src: '/showcase/workshop-day2-03.jpg', alt: 'Envision — workshop day2 03' },
  { id: 'workshop-day2-04', src: '/showcase/workshop-day2-04.jpg', alt: 'Envision — workshop day2 04' },
  { id: 'workshop-day2-05', src: '/showcase/workshop-day2-05.jpg', alt: 'Envision — workshop day2 05' },
  { id: 'workshop-day2-06', src: '/showcase/workshop-day2-06.jpg', alt: 'Envision — workshop day2 06' },
  { id: 'workshop-day2-07', src: '/showcase/workshop-day2-07.jpg', alt: 'Envision — workshop day2 07' },
  { id: 'workshop-day2-08', src: '/showcase/workshop-day2-08.jpg', alt: 'Envision — workshop day2 08' },
  { id: 'workshop-day2-09', src: '/showcase/workshop-day2-09.jpg', alt: 'Envision — workshop day2 09' },
  { id: 'workshop-day2-10', src: '/showcase/workshop-day2-10.jpg', alt: 'Envision — workshop day2 10' },
  { id: 'workshop-day2-11', src: '/showcase/workshop-day2-11.jpg', alt: 'Envision — workshop day2 11' },
  { id: 'workshop-day2-12', src: '/showcase/workshop-day2-12.jpg', alt: 'Envision — workshop day2 12' },
  { id: 'workshop-day2-13', src: '/showcase/workshop-day2-13.jpg', alt: 'Envision — workshop day2 13' },
  { id: 'workshop-day2-14', src: '/showcase/workshop-day2-14.jpg', alt: 'Envision — workshop day2 14' },
  { id: 'workshop-day2-15', src: '/showcase/workshop-day2-15.jpg', alt: 'Envision — workshop day2 15' },
  { id: 'workshop-day2-16', src: '/showcase/workshop-day2-16.jpg', alt: 'Envision — workshop day2 16' },
  { id: 'workshop-day2-17', src: '/showcase/workshop-day2-17.jpg', alt: 'Envision — workshop day2 17' },
  { id: 'workshop-day2-18', src: '/showcase/workshop-day2-18.jpg', alt: 'Envision — workshop day2 18' },
  { id: 'workshop-day2-19', src: '/showcase/workshop-day2-19.jpg', alt: 'Envision — workshop day2 19' },
  { id: 'workshop-day2-20', src: '/showcase/workshop-day2-20.jpg', alt: 'Envision — workshop day2 20' },
  { id: 'workshop-day2-21', src: '/showcase/workshop-day2-21.jpg', alt: 'Envision — workshop day2 21' },
  { id: 'workshop-day2-22', src: '/showcase/workshop-day2-22.jpg', alt: 'Envision — workshop day2 22' },
  { id: 'workshop-day2-23', src: '/showcase/workshop-day2-23.jpg', alt: 'Envision — workshop day2 23' },
  { id: 'workshop-day2-24', src: '/showcase/workshop-day2-24.jpg', alt: 'Envision — workshop day2 24' },
  { id: 'workshop-day2-25', src: '/showcase/workshop-day2-25.jpg', alt: 'Envision — workshop day2 25' },
  { id: 'workshop-day2-26', src: '/showcase/workshop-day2-26.jpg', alt: 'Envision — workshop day2 26' },
  { id: 'workshop-day2-27', src: '/showcase/workshop-day2-27.jpg', alt: 'Envision — workshop day2 27' },
  { id: 'workshop-day2-28', src: '/showcase/workshop-day2-28.jpg', alt: 'Envision — workshop day2 28' },
  { id: 'workshop-day2-29', src: '/showcase/workshop-day2-29.jpg', alt: 'Envision — workshop day2 29' },
]
